### ISSUE TITLE
AIPersonality: The provided path does not exist.

### ISSUE THREAD

**Issue by jagbarcelo** [ParisNeo/lollms-webui#148]
## Expected Behavior
Executing `webui.bat` should download dependencies and end listening for commands on http://localhost:9600

## Current Behavior
Executing webui.bat ends with the following error:

```
...
Checking models...
gpt4all-lora-quantized-ggml.bin
Model already installed
Virtual environment created and packages installed successfully.
Launching application...
No local configuration file found. Building from scratch
Traceback (most recent call last):
  File "D:\gpt4all-ui\GPT4All\app.py", line 736, in <module>
    personality = AIPersonality(f"personalities/{config['personality_language']}/{config['personality_category']}/{config['personality']}")
  File "D:\gpt4all-ui\GPT4All\env\lib\site-packages\pyaipersonality\__init__.py", line 82, in __init__
    raise ValueError("The provided path does not exist.")
ValueError: The provided path does not exist.

```

## Steps to Reproduce

1. Download webui.bat and place it into a new empty directory, for instance D:\gpt4all-ui\
2. Execute webui.bat
3. Wait for the error to happen

## Possible Solution
Everything was working just fine 2 hours ago. There must be something wrong with the some of the recent commits.

<img width="946" alt="image" src="https://user-images.githubusercontent.com/6704109/236475598-79f116b7-21cb-4ad3-88ff-9f0ec19f8dad.png">

**Comment by ParisNeo** [comment]
Yes I lnow whjat's wrong

the default gpt4all category has changed from general to generic.

Just change that in your configs/config_local.yaml

**Comment by andzejsp** [comment]
removing config_local.yaml usually helps to reset and update default values.. it regenerates after launch

**Comment by jagbarcelo** [comment]
Both my `/configs/default.yaml` and `/configs/local_default.yaml` contain:

```
personality_language: english
personality_category: generic
```

The problem also occurs from a brand-new-empty reinstall through `webui.bat`

Also tried removing `local_default.yaml` (which is regenerated with the next run), but the problem persists.

**Comment by jagbarcelo** [comment]
Editing `local_default.yaml` and setting `personality_category: generic` does not fix anything. It does not work setting `personality_category: general` either.

I have even removed the whole `GPT4All` directory and let the autoinstall download everything again. The error is still there.

**Comment by jagbarcelo** [comment]
I think I figured out the problem. It seems the `webui.bat` installer, as it is configured right now, does not install **any** personalities (the folder `/personalities` did not exist after running `webui.bat` for the first time).

I have **manually** run `add_personality.bat` selecting the options:
```
Enter the number of the desired language: 1 (English)
Enter the number of the desired category: 12 (generic)
Enter the number of the desired personality: 1 (gpt4all)
```

After that, `webui.bat` runs fine. Maybe you need to update it and check that at least the default personality exists.

**Comment by andzejsp** [comment]
"someone" made a big oopsy.. gonna check what i can do to fix this

**Comment by ParisNeo** [comment]
Problem fixed. Please just do a pull

**Comment by ParisNeo** [comment]
now there are no personalities by default
The personalities folder is empty
and by default a gpt4all hardcoded in the app is used
When people mess up their personalities, this will garantee that the app will continue working.
you can install new personalities using add_personality.bat file

**Comment by loup73** [comment]
The issue persists on Ubuntu even after running add_personality.sh. I pulled tand installed the repo today, run.sh returns the error.

**Comment by loup73** [comment]
I try to run this on a properly protected public page that proxies to localhost:9600 of a local machine. Any hints on how to overcome random errors related to dialog loading, timeouts when returning etc? So far what I've done was adding upgrade-insecure-requests to the index.html page, to be able to route from https to http, which made the basic functionality of asking a question, available. Can it serve multiple parallel requests, as an example?

**Comment by andzejsp** [comment]
> I try to run this on a properly protected public page that proxies to localhost:9600 of a local machine. Any hints on how to overcome random errors related to dialog loading, timeouts when returning etc? So far what I've done was adding upgrade-insecure-requests to the index.html page, to be able to route from https to http, which made the basic functionality of asking a question, available. Can it serve multiple parallel requests, as an example?

not sure what if its possible on old UI, but new UI works well behind a proxy, i run it daily  to test the new UI. check out the local_defaults.yaml in the configs for ui flags. 

As for concurrent replies, i dont think its implemented yet. It is planned, not by me but by main dev. Not sure when tho.

**Comment by andzejsp** [comment]
Is this issue resolved?

**Comment by Rejoov** [comment]
Im still having this issue and none of the steps above resolve it.
