### ISSUE TITLE
ERROR - Exception on /list_personalities_categories [GET]

### ISSUE THREAD

**Issue by wwwwwuxueyu** [ParisNeo/lollms-webui#177]
[2023-05-11 18:07:36,426] {app.py:1414} ERROR - Exception on /list_personalities_categories [GET]
Traceback (most recent call last):
  File "/home/wxy/anaconda3/envs/gpt/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/wxy/anaconda3/envs/gpt/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/wxy/anaconda3/envs/gpt/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/wxy/anaconda3/envs/gpt/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/wxy/桌面/GPT4ALL/gpt4all-ui/app.py", line 389, in list_personalities_categories
    personalities_categories = [f.stem for f in personalities_categories_dir.iterdir() if f.is_dir()]
  File "/home/wxy/桌面/GPT4ALL/gpt4all-ui/app.py", line 389, in <listcomp>
    personalities_categories = [f.stem for f in personalities_categories_dir.iterdir() if f.is_dir()]
  File "/home/wxy/anaconda3/envs/gpt/lib/python3.10/pathlib.py", line 1017, in iterdir
    for name in self._accessor.listdir(self):
FileNotFoundError: [Errno 2] No such file or directory: 'personalities/english'
[2023-05-11 18:07:36,430] {app.py:1414} ERROR - Exception on /list_personalities_languages [GET]
Traceback (most recent call last):
  File "/home/wxy/anaconda3/envs/gpt/lib/python3.10/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/wxy/anaconda3/envs/gpt/lib/python3.10/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/wxy/anaconda3/envs/gpt/lib/python3.10/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/wxy/anaconda3/envs/gpt/lib/python3.10/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/wxy/桌面/GPT4ALL/gpt4all-ui/app.py", line 384, in list_personalities_languages
    personalities_languages = [f.stem for f in personalities_languages_dir.iterdir() if f.is_dir()]
  File "/home/wxy/桌面/GPT4ALL/gpt4all-ui/app.py", line 384, in <listcomp>
    personalities_languages = [f.stem for f in personalities_languages_dir.iterdir() if f.is_dir()]
  File "/home/wxy/anaconda3/envs/gpt/lib/python3.10/pathlib.py", line 1017, in iterdir
    for name in self._accessor.listdir(self):
FileNotFoundError: [Errno 2] No such file or directory: 'personalities'

**Comment by andzejsp** [comment]
FileNotFoundError: [Errno 2] No such file or directory: 'personalities'

https://github.com/nomic-ai/gpt4all-ui#personality-install

Search for install script under `/gpt4all-ui/installations/`
