### ISSUE TITLE
lollms-webui\\env\\lib\\site-packages\\lollms\\models.yaml no such file or directory

### ISSUE THREAD

**Issue by rempel1234** [ParisNeo/lollms-webui#270]
## Expected Behavior
Selection of GPT-J-a binding is successful

## Current Behavior
Get the following error message

ERROR:GPT4All-WebUI:Exception on /get_available_models [GET]
Traceback (most recent call last):
  File "C:\Users\KDieb\Documents\lollms-webui\env\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\KDieb\Documents\lollms-webui\env\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\KDieb\Documents\lollms-webui\env\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\KDieb\Documents\lollms-webui\env\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\KDieb\Documents\lollms-webui\app.py", line 996, in get_available_models
    model_list = self.binding.get_available_models()
  File "C:\Users\KDieb\Documents\lollms-webui\env\lib\site-packages\lollms\binding.py", line 214, in get_available_models
    with open(file_path, 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\KDieb\\Documents\\lollms-webui\\env\\lib\\site-packages\\lollms\\models.yaml'

## Steps to Reproduce
Please provide detailed steps to reproduce the issue.

1. launch webui.bat
2. Click settings
3. Expand Binding zoo
4. Click GPT-J-a

## Possible Solution
If the file is not found, add an exception handler that copies the file from somewhere else, and tries again

## Context
Windows 11, gitbash

## Screenshots
If applicable, add screenshots to help explain the issue.

<img width="943" alt="image" src="https://github.com/ParisNeo/lollms-webui/assets/135683081/7f20dc8f-7d76-4847-af4c-30f81edc8b41">

**Comment by ParisNeo** [comment]
I guess the model.yaml has some errors, i'll fix them.

**Comment by rempel1234** [comment]
Wow! You're really responsive :) Thanks for all your help!

**Comment by ParisNeo** [comment]
The binding has been fixed. You need to run the webui script or upgrade lollms library and pull last changes from the lollms-webui
