### ISSUE TITLE
Model wont download from model zoo

### ISSUE THREAD

**Issue by alekbj16** [ParisNeo/lollms-webui#311]
## Expected Behavior
Model should download

## Current Behavior
Download speed is stuck at 0 B/s. No progress. 

## Screenshots
If applicable, add screenshots to help explain the issue.
![image](https://github.com/ParisNeo/lollms-webui/assets/59872936/50eac9bc-abcb-45c3-b170-2ed8ee9b9806)

**Comment by ParisNeo** [comment]
What does the console say?

**Comment by alekbj16** [comment]
`
Install model triggered
Model install requested
Model path : https://huggingface.co/TheBloke/starcoderplus-GGML/resolve/main/starcoderplus.ggmlv3.q4_1.bin
Exception in thread Thread-1 (install_model_):
Traceback (most recent call last):
  File "C:\Users\rg-vm-starcoder-adm\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\Users\rg-vm-starcoder-adm\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1286, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\rg-vm-starcoder-adm\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1332, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\rg-vm-starcoder-adm\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1281, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\rg-vm-starcoder-adm\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1041, in _send_output
    self.send(msg)
  File "C:\Users\rg-vm-starcoder-adm\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 979, in send
    self.connect()
  File "C:\Users\rg-vm-starcoder-adm\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1458, in connect
    self.sock = self._context.wrap_socket(self.sock,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rg-vm-starcoder-adm\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rg-vm-starcoder-adm\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1075, in _create
    self.do_handshake()
  File "C:\Users\rg-vm-starcoder-adm\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 1346, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\rg-vm-starcoder-adm\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\rg-vm-starcoder-adm\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\rg-vm-starcoder-adm\Documents\gpt4all-webui\lollms-webui\api\__init__.py", line 205, in install_model_
    "total_size":get_file_size(model_path),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rg-vm-starcoder-adm\Documents\gpt4all-webui\lollms-webui\api\__init__.py", line 178, in get_file_size
    response = urllib.request.urlopen(url)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rg-vm-starcoder-adm\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rg-vm-starcoder-adm\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 519, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rg-vm-starcoder-adm\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rg-vm-starcoder-adm\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "C:\Users\rg-vm-starcoder-adm\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rg-vm-starcoder-adm\AppData\Local\Programs\Python\Python311\Lib\urllib\request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)>


`

**Comment by alekbj16** [comment]
What do I need to do in terms of certificates?

**Comment by ParisNeo** [comment]
Hi. Are you hiding behind a firewall or are you using a proxy or vpn?

**Comment by vlsalsa** [comment]
Is there a way to add an option for --no-check-certificates to the code as well? 

I have a similar issue but manually downloading using wget and that flag works for me
