### ISSUE TITLE
linux_install.sh massively improved, but conda errors out

### ISSUE THREAD

**Issue by sdrakulich** [ParisNeo/lollms-webui#328]
## Expected Behavior
Fresh dir, no weird symbols in path or too long, `./linux_install.sh` (color me impressed btw, you're doing a ton of work it's obvious)

Installs ok. `./linux_run.sh` fails as per below
`./linux_update` pretty sure is the same error

```
<snipped>

File "/home/user/Git/LOLLMS/installer_files/miniconda3/lib/python3.11/site-packages/conda/activate.py", line 691, in _prompt_modifier
        old_shlvl = int(self.environ.get("CONDA_SHLVL", "0").rstrip())
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ValueError: invalid literal for int() with base 10: ''

`$ /home/user/Git/LOLLMS/installer_files/miniconda3/bin/conda shell.posix activate ./installer_files/lollms_env`

  environment variables:
conda info could not be constructed.
KeyError('pkgs_dirs')

An unexpected error has occurred. Conda has prepared the above report.
```

Going to try clearing caches and rebooting and friends, on my end

**Comment by mreitschuster** [comment]
same error here.  

```
Starting LOLLMS Web UI...
      ___       ___           ___       ___       ___           ___      
     /\__\     /\  \         /\__\     /\__\     /\__\         /\  \     
    /:/  /    /::\  \       /:/  /    /:/  /    /::|  |       /::\  \    
   /:/  /    /:/\:\  \     /:/  /    /:/  /    /:|:|  |      /:/\ \  \   
  /:/  /    /:/  \:\  \   /:/  /    /:/  /    /:/|:|__|__   _\:\~\ \  \  
 /:/__/    /:/__/ \:\__\ /:/__/    /:/__/    /:/ |::::\__\ /\ \:\ \ \__\ 
 \:\  \    \:\  \ /:/  / \:\  \    \:\  \    \/__/~~/:/  / \:\ \:\ \/__/ 
  \:\  \    \:\  /:/  /   \:\  \    \:\  \         /:/  /   \:\ \:\__\   
   \:\  \    \:\/:/  /     \:\  \    \:\  \       /:/  /     \:\/:/  /   
    \:\__\    \::/  /       \:\__\    \:\__\     /:/  /       \::/  /    
     \/__/     \/__/         \/__/     \/__/     \/__/         \/__/     
 By ParisNeo
WARNING conda.exception_handler:print_unexpected_error_report(168): KeyError('pkgs_dirs')
Traceback (most recent call last):
  File "/home/user/srv/lollms-webui/installer_files/miniconda3/lib/python3.11/site-packages/conda/exception_handler.py", line 16, in __call__
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/srv/lollms-webui/installer_files/miniconda3/lib/python3.11/site-packages/conda/cli/main.py", line 111, in main_sourced
    print(activator.execute(), end="")
          ^^^^^^^^^^^^^^^^^^^
  File "/home/user/srv/lollms-webui/installer_files/miniconda3/lib/python3.11/site-packages/conda/activate.py", line 191, in execute
    return getattr(self, self.command)()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/srv/lollms-webui/installer_files/miniconda3/lib/python3.11/site-packages/conda/activate.py", line 157, in activate
    builder_result = self.build_activate(self.env_name_or_prefix)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/srv/lollms-webui/installer_files/miniconda3/lib/python3.11/site-packages/conda/activate.py", line 335, in build_activate
    return self._build_activate_stack(env_name_or_prefix, False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/srv/lollms-webui/installer_files/miniconda3/lib/python3.11/site-packages/conda/activate.py", line 364, in _build_activate_stack
    conda_prompt_modifier = self._prompt_modifier(prefix, conda_default_env)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/srv/lollms-webui/installer_files/miniconda3/lib/python3.11/site-packages/conda/activate.py", line 691, in _prompt_modifier
    old_shlvl = int(self.environ.get("CONDA_SHLVL", "0").rstrip())
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/srv/lollms-webui/installer_files/miniconda3/lib/python3.11/site-packages/conda/exception_handler.py", line 165, in print_unexpected_error_report
    get_main_info_str(error_report["conda_info"])
  File "/home/user/srv/lollms-webui/installer_files/miniconda3/lib/python3.11/site-packages/conda/cli/main_info.py", line 250, in get_main_info_str
    info_dict["_" + key] = ("\n" + 26 * " ").join(info_dict[key])
                                                  ~~~~~~~~~^^^^^
KeyError: 'pkgs_dirs'

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/user/srv/lollms-webui/installer_files/miniconda3/lib/python3.11/site-packages/conda/exception_handler.py", line 16, in __call__
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "/home/user/srv/lollms-webui/installer_files/miniconda3/lib/python3.11/site-packages/conda/cli/main.py", line 111, in main_sourced
        print(activator.execute(), end="")
              ^^^^^^^^^^^^^^^^^^^
      File "/home/user/srv/lollms-webui/installer_files/miniconda3/lib/python3.11/site-packages/conda/activate.py", line 191, in execute
        return getattr(self, self.command)()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/user/srv/lollms-webui/installer_files/miniconda3/lib/python3.11/site-packages/conda/activate.py", line 157, in activate
        builder_result = self.build_activate(self.env_name_or_prefix)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/user/srv/lollms-webui/installer_files/miniconda3/lib/python3.11/site-packages/conda/activate.py", line 335, in build_activate
        return self._build_activate_stack(env_name_or_prefix, False)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/user/srv/lollms-webui/installer_files/miniconda3/lib/python3.11/site-packages/conda/activate.py", line 364, in _build_activate_stack
        conda_prompt_modifier = self._prompt_modifier(prefix, conda_default_env)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/user/srv/lollms-webui/installer_files/miniconda3/lib/python3.11/site-packages/conda/activate.py", line 691, in _prompt_modifier
        old_shlvl = int(self.environ.get("CONDA_SHLVL", "0").rstrip())
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ValueError: invalid literal for int() with base 10: ''

`$ /home/user/srv/lollms-webui/installer_files/miniconda3/bin/conda shell.posix activate ./installer_files/lollms_env`

  environment variables:
conda info could not be constructed.
KeyError('pkgs_dirs')

An unexpected error has occurred. Conda has prepared the above report.


Timeout reached. No report sent.

Traceback (most recent call last):
  File "/home/user/srv/lollms-webui/lollms-webui/app.py", line 27, in <module>
    from lollms.config import InstallOption
ModuleNotFoundError: No module named 'lollms'
./linux_run.sh: line 42: pause: command not found

```
thought it might be a conda error, so i played around a bit with conda envs, but no improvement.

**Comment by ParisNeo** [comment]
Hi, here conda is erroring out.
Do you have a conda instance already installed on your PC?

**Comment by mreitschuster** [comment]
Thank you for the hint. I can confirm:
- on a Ubuntu in which I dont have anaconda installed -> works
- on a Ubuntu in which I have anaconda installed -> error from above

**Comment by Israr** [comment]
I was encountering same issue (using ubuntu 20.04, with conda pre-installed). I was able to fix the error using following command

`unset CONDA_SHLVL`

**Comment by ParisNeo** [comment]
Hi. For people who have their own conda environment, please use the [linux_install_use_your_own_conda.sh](https://github.com/ParisNeo/lollms-webui/blob/main/scripts/linux/linux_install_use_your_own_conda.sh) script instead.

It will install lollms without installing conda. and it will use your own conda to install packages.
