### ISSUE TITLE
Couldn't load model: [[WinError 3] The system cannot find the path specified:

### ISSUE THREAD

**Issue by divyanshverma** [ParisNeo/lollms-webui#332]
## Expected Behavior
After a model is downloaded , it should be installed successfully.

## Current Behavior
After the model is downloaded, when I try to set it but getting the below error:

Couldn't load model: [[WinError 3] The system cannot find the path specified: 'C:\\Users\\Divy\\WebstormProjects\\lollms2\\models\\gptq\\airoboros-13B-1.1-GPTQ']
Traceback (most recent call last):
  File "C:\Users\Divy\WebstormProjects\lollms-webui\lollms-webui\app.py", line 619, in update_setting
    self.model = self.binding.build_model()
  File "C:\Users\Divy\WebstormProjects\lollms2\bindings_zoo\gptq\__init__.py", line 115, in build_model
    model_base_name = [f for f in model_path.iterdir() if f.suffix==".safetensors"][0].stem
  File "C:\Users\Divy\WebstormProjects\lollms2\bindings_zoo\gptq\__init__.py", line 115, in <listcomp>
    model_base_name = [f for f in model_path.iterdir() if f.suffix==".safetensors"][0].stem
  File "C:\Users\Divy\WebstormProjects\lollms-webui\installer_files\lollms_env\lib\pathlib.py", line 1017, in iterdir
    for name in self._accessor.listdir(self):
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\Divy\\WebstormProjects\\lollms2\\models\\gptq\\airoboros-13B-1.1-GPTQ'

Couldn't load model: [[WinError 3] The system cannot find the path specified: 'C:\\Users\\Divy\\WebstormProjects\\lollms2\\models\\gptq\\chronos-hermes-13B-GPTQ']
Traceback (most recent call last):
  File "C:\Users\Divy\WebstormProjects\lollms-webui\lollms-webui\app.py", line 619, in update_setting
    self.model = self.binding.build_model()
  File "C:\Users\Divy\WebstormProjects\lollms2\bindings_zoo\gptq\__init__.py", line 115, in build_model
    model_base_name = [f for f in model_path.iterdir() if f.suffix==".safetensors"][0].stem
  File "C:\Users\Divy\WebstormProjects\lollms2\bindings_zoo\gptq\__init__.py", line 115, in <listcomp>
    model_base_name = [f for f in model_path.iterdir() if f.suffix==".safetensors"][0].stem
  File "C:\Users\Divy\WebstormProjects\lollms-webui\installer_files\lollms_env\lib\pathlib.py", line 1017, in iterdir
    for name in self._accessor.listdir(self):
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\Divy\\WebstormProjects\\lollms2\\models\\gptq\\chronos-hermes-13B-GPTQ'
## Steps to Reproduce
Please provide detailed steps to reproduce the issue.

1. Select any Binding and save the changes.
2. Go the model binding and install a model.
3. After its installed, select it .
4. Observe the error in console.

## Possible Solution
If you have any suggestions on how to fix the issue, please describe them here.

## Context
Environment :
WIndows 11 Pro
Python: 3.11
Conda

## Screenshots
![Screenshot 2023-07-21 232258](https://github.com/ParisNeo/lollms-webui/assets/13277557/d1279e0d-a198-4561-879c-160d13764cac)

**Comment by soladragon** [comment]
Hi, I have this issue. What caused it?

**Comment by divyanshverma** [comment]
So I was missing this [auto_gptq-0.3.0+cu117-cp310-cp310-linux_x86_64.whl] file for my setup based on python 3.11
After I installed this, all works nows.

This 
(https://github.com/PanQiWei/AutoGPTQ/releases/download/v0.3.0/auto_gptq-0.3.0+cu117-cp310-cp310-linux_x86_64.whl)
