### ISSUE TITLE
Thread

### ISSUE THREAD

**Issue by sam43b** [ParisNeo/lollms-webui#334]
hi,

thank you so much for this wonderful framework,however, i get this error message , i'm using many ggml with pyllamacpp , i have AMD Ryzen 7 3700X 8-Core , and 32Go of ram

Text generation requested by client: bl_dcSQi6UQTKzyNAAAB
Received message : Write an email to my boss letting them know I am leaving the company.
Started generation task
warmup for generating 1716 tokens
Client bl_dcSQi6UQTKzyNAAAB disconnected
'bl_dcSQi6UQTKzyNAAAB'

Finished executing the generation

## Done Generation ##

Exception in thread Thread-92 (start_message_generation):
Traceback (most recent call last):
  File "/home/sam/appz/llm/vnv/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/sam/appz/llm/vnv/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/sam/appz/llm/lollms-webui/api/__init__.py", line 946, in start_message_generation
    self.current_discussion.update_message(self.current_ai_message_id, self.connections[client_id]["generated_text"].strip())
KeyError: 'bl_dcSQi6UQTKzyNAAAB'
Client syJfYZAgBSmDEWNKAAAD connected

**Comment by ParisNeo** [comment]
Looks like something happened that caused the front end to disconnect.
Zre you using it remotely ?

**Comment by sam43b** [comment]
yes , i'm using it remotely on linux ubuntu 20.04

**Comment by Nha-Krul** [comment]
Hi Parisneo.
I'm having the same issue. And the disconnections are more frequents if I use a reverse proxy.
Today I get this exception, maybe it helps.

Exception in thread Thread-72 (_thread):
Traceback (most recent call last):
Client euHA3MuNS--XMw9mAAAI disconnected
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/marcelo/software/lollms-webui/env/lib/python3.10/site-packages/simple_websocket/ws.py", line 169, in _thread
Client 5xkgVElOTZI34ppDAAAL connected
    self.connected = self._handle_events()
  File "/home/marcelo/software/lollms-webui/env/lib/python3.10/site-packages/simple_websocket/ws.py", line 249, in _handle_events
    self.sock.send(out_data)
BrokenPipeError: [Errno 32] Broken pipe
