### ISSUE TITLE
linux PosixPath

### ISSUE THREAD

**Issue by sam43b** [ParisNeo/lollms-webui#335]
Hi,

i have linux ubuntu 22.04 , i get this error on a new installation using manual install steps

No binding selected
Please select a valid model or install a new one from a url
unsupported operand type(s) for /: 'PosixPath' and 'NoneType'
Couldn't find binding. Please verify your configuration file at /home/sam/appz/nlp/lollms-webui/cnf/configs/local_configs.yaml or use the next menu to select a valid binding
Trying to reinstall binding
Couldn't reinstall model
Traceback (most recent call last):
  File "/home/sam/appz/nlp/vnv/lib/python3.10/site-packages/lollms/app.py", line 77, in load_binding
    binding = BindingBuilder().build_binding(self.config, self.lollms_paths)
  File "/home/sam/appz/nlp/vnv/lib/python3.10/site-packages/lollms/binding.py", line 284, in build_binding
    binding_path = lollms_paths.bindings_zoo_path / config["binding_name"]
TypeError: unsupported operand type(s) for /: 'PosixPath' and 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sam/appz/nlp/vnv/lib/python3.10/site-packages/lollms/app.py", line 84, in load_binding
    binding = BindingBuilder().build_binding(self.config, self.lollms_paths,installation_option=InstallOption.FORCE_INSTALL)
  File "/home/sam/appz/nlp/vnv/lib/python3.10/site-packages/lollms/binding.py", line 284, in build_binding
    binding_path = lollms_paths.bindings_zoo_path / config["binding_name"]
TypeError: unsupported operand type(s) for /: 'PosixPath' and 'NoneType'

Couldn't load binding None.

**Comment by sam43b** [comment]
Hi, 

the last version (v3.5) don't fix this issue , this will skip the binding installation menu , and if i install the binding from the web ui
some ggml models will not load. i hope if you can fix this problem soon , and please , add to the webui the possibility to select a local model from the HDD, without download.

No extensions found in your personal space.
Cloning the extensions zoo
Clonage dans '/home/sam/appz/nlp/lollms-webui/cnf/extensions_zoo_path'...
remote: Enumerating objects: 12, done.
remote: Counting objects: 100% (12/12), done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 12 (delta 1), reused 7 (delta 0), pack-reused 0
Réception d'objets: 100% (12/12), 6.56 Kio | 6.56 Mio/s, fait.
Résolution des deltas: 100% (1/1), fait.
No binding selected
unsupported operand type(s) for /: 'PosixPath' and 'NoneType'
Couldn't find binding. Please verify your configuration file at /home/sam/appz/n                                                                                                                                                             lp/lollms-webui/cnf/configs/local_configs.yaml or use the next menu to select a                                                                                                                                                              valid binding
Trying to reinstall binding
Couldn't reinstall model
Traceback (most recent call last):
  File "/home/sam/appz/nlp/vnv/lib/python3.10/site-packages/lollms/app.py", line                                                                                                                                                              77, in load_binding
    binding = BindingBuilder().build_binding(self.config, self.lollms_paths)
  File "/home/sam/appz/nlp/vnv/lib/python3.10/site-packages/lollms/binding.py",                                                                                                                                                              line 284, in build_binding
    binding_path = lollms_paths.bindings_zoo_path / config["binding_name"]
TypeError: unsupported operand type(s) for /: 'PosixPath' and 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sam/appz/nlp/vnv/lib/python3.10/site-packages/lollms/app.py", line                                                                                                                                                              84, in load_binding
    binding = BindingBuilder().build_binding(self.config, self.lollms_paths,inst                                                                                                                                                             allation_option=InstallOption.FORCE_INSTALL)
  File "/home/sam/appz/nlp/vnv/lib/python3.10/site-packages/lollms/binding.py",                                                                                                                                                              line 284, in build_binding
    binding_path = lollms_paths.bindings_zoo_path / config["binding_name"]
TypeError: unsupported operand type(s) for /: 'PosixPath' and 'NoneType'

Couldn't load binding None.
Personality  lollms mounted successfully but no model is selected
Checking discussions database... ok
Your personal data is stored here :/home/sam/appz/nlp/lollms-webui/cnf
Your personal data is stored here :/home/sam/appz/nlp/lollms-webui/cnf
debug mode:false
Please open your browser and go to http://localhost:9600 to view the ui

**Comment by sam43b** [comment]
Hi,

i get also a problem when i try to install artbot_2

*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
Installing artbot_2
*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
Service did not become available within the given time.
Personality file not found or is corrupted (/home/sam/appz/llm/lollms-webui/cnf/personalities_zoo/english/art/artbot_2).
Returned the following exception:[Errno 13] Permission denied: PosixPath('/home/sam/appz/llm/lollms-webui/cnf/shared/auto_sd/lollms_webui.sh')
Please verify that the personality you have selected exists or select another personality. Some updates may lead to change in personality name or category, so check the personality selection in settings to be sure.
Trying to force reinstall
*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
Installing artbot_2
*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
Service did not become available within the given time.
Couldn't load personality at /home/sam/appz/llm/lollms-webui/cnf/personalities_zoo/english/art/artbot_2
Traceback (most recent call last):
  File "/home/sam/appz/llm/lollms-webui/api/__init__.py", line 519, in rebuild_personalities
    personality = AIPersonality(personality_path,
  File "/home/sam/appz/llm/vnv/lib/python3.10/site-packages/lollms/personality.py", line 153, in __init__
    self.load_personality(personality_package_path)
  File "/home/sam/appz/llm/vnv/lib/python3.10/site-packages/lollms/personality.py", line 251, in load_personality
    self._processor = module.Processor(self)
  File "/home/sam/appz/llm/lollms-webui/cnf/personalities_zoo/english/art/artbot_2/scripts/processor.py", line 58, in __init__
    super().__init__(
  File "/home/sam/appz/llm/vnv/lib/python3.10/site-packages/lollms/personality.py", line 936, in __init__
    self.install()
  File "/home/sam/appz/llm/lollms-webui/cnf/personalities_zoo/english/art/artbot_2/scripts/processor.py", line 79, in install
    self.prepare()
  File "/home/sam/appz/llm/lollms-webui/cnf/personalities_zoo/english/art/artbot_2/scripts/processor.py", line 85, in prepare
    self.sd = self.get_sd().SD(self.personality.lollms_paths, self.personality_config, max_retries=-1)
  File "/home/sam/appz/llm/lollms-webui/cnf/shared/auto_sd/lollms_sd.py", line 35, in __init__
    subprocess.Popen(script_path, cwd=self.sd_folder)
  File "/home/sam/appz/llm/vnv/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/sam/appz/llm/vnv/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: PosixPath('/home/sam/appz/llm/lollms-webui/cnf/shared/auto_sd/lollms_webui.sh')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sam/appz/llm/lollms-webui/api/__init__.py", line 531, in rebuild_personalities
    personality = AIPersonality(
  File "/home/sam/appz/llm/vnv/lib/python3.10/site-packages/lollms/personality.py", line 153, in __init__
    self.load_personality(personality_package_path)
  File "/home/sam/appz/llm/vnv/lib/python3.10/site-packages/lollms/personality.py", line 251, in load_personality
    self._processor = module.Processor(self)
  File "/home/sam/appz/llm/lollms-webui/cnf/personalities_zoo/english/art/artbot_2/scripts/processor.py", line 58, in __init__
    super().__init__(
  File "/home/sam/appz/llm/vnv/lib/python3.10/site-packages/lollms/personality.py", line 936, in __init__
    self.install()
  File "/home/sam/appz/llm/lollms-webui/cnf/personalities_zoo/english/art/artbot_2/scripts/processor.py", line 79, in install
    self.prepare()
  File "/home/sam/appz/llm/lollms-webui/cnf/personalities_zoo/english/art/artbot_2/scripts/processor.py", line 85, in prepare
    self.sd = self.get_sd().SD(self.personality.lollms_paths, self.personality_config, max_retries=-1)
  File "/home/sam/appz/llm/lollms-webui/cnf/shared/auto_sd/lollms_sd.py", line 35, in __init__
    subprocess.Popen(script_path, cwd=self.sd_folder)
  File "/home/sam/appz/llm/vnv/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/sam/appz/llm/vnv/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: PosixPath('/home/sam/appz/llm/lollms-webui/cnf/shared/auto_sd/lollms_webui.sh')
