### ISSUE TITLE
Unable to install personalities - Latest - Ubuntu 22.04

### ISSUE THREAD

**Issue by DrGood01** [ParisNeo/lollms-webui#346]
## Expected Behavior
Mount, or Install a personality.

## Current Behavior
After clicking on Mount, console output is:

`* english/generic/gpt4all
 english/generic/chain_of_thoughts
Personality file not found or is corrupted (/home/jane/Documents/lollms/personalities_zoo/english/generic/chain_of_thoughts).
Returned the following exception:No module named 'pyaipersonality'
Please verify that the personality you have selected exists or select another personality. Some updates may lead to change in personality name or category, so check the personality selection in settings to be sure.
Trying to force reinstall
Couldn't load personality at /home/jane/Documents/lollms/personalities_zoo/english/generic/chain_of_thoughts
Traceback (most recent call last):
  File "/home/jane/.local/share/Trash/files/lollms-webui/api/__init__.py", line 615, in rebuild_personalities
    personality = AIPersonality(personality_path,
  File "/home/jane/.local/share/Trash/files/lollms-webui/env/lib/python3.10/site-packages/lollms/personality.py", line 156, in __init__
    self.load_personality(personality_package_path)
  File "/home/jane/.local/share/Trash/files/lollms-webui/env/lib/python3.10/site-packages/lollms/personality.py", line 258, in load_personality
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/jane/Documents/lollms/personalities_zoo/english/generic/chain_of_thoughts/scripts/processor.py", line 7, in <module>
    from pyaipersonality import PAPScript, AIPersonality, MSG_TYPE
ModuleNotFoundError: No module named 'pyaipersonality'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jane/.local/share/Trash/files/lollms-webui/api/__init__.py", line 627, in rebuild_personalities
    personality = AIPersonality(
  File "/home/jane/.local/share/Trash/files/lollms-webui/env/lib/python3.10/site-packages/lollms/personality.py", line 156, in __init__
    self.load_personality(personality_package_path)
  File "/home/jane/.local/share/Trash/files/lollms-webui/env/lib/python3.10/site-packages/lollms/personality.py", line 258, in load_personality
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/jane/Documents/lollms/personalities_zoo/english/generic/chain_of_thoughts/scripts/processor.py", line 7, in <module>
    from pyaipersonality import PAPScript, AIPersonality, MSG_TYPE
ModuleNotFoundError: No module named 'pyaipersonality'

Unmounting personality
Reverted to default personality
`

## Steps to Reproduce
Please provide detailed steps to reproduce the issue.

1. Step 1
2. Step 2
3. Step 3

## Possible Solution
If you have any suggestions on how to fix the issue, please describe them here.

## Context
Please provide any additional context about the issue.

## Screenshots
If applicable, add screenshots to help explain the issue.

**Comment by ParisNeo** [comment]
This is one month ago. For a tool that has now 5 months of existance time, this is very long time.
All this has completely changed. So please try again and oif you still have problems come back or better go to the discord channel as I mostly answer people there:
https://discord.gg/hFEY44RB
I hopre this helps
