### ISSUE TITLE
Arbot2

### ISSUE THREAD

**Issue by agustin9014** [ParisNeo/lollms-webui#359]
hello paris neo, congratulations and success with this beautiful project! You know that artbot is not working to create images. thank you so much

**Comment by agustin9014** [comment]
Git pull successful in /root/Documents/lollms/shared/auto_sd
Service did not become available within the given time.
Couldn't load personality at /root/Documents/lollms/personalities_zoo/art/artbot
Traceback (most recent call last):
  File "/root/lollms-webui/api/__init__.py", line 857, in rebuild_personalities
    personality = AIPersonality(personality_path,
  File "/root/installer_files/lollms_env/lib/python3.10/site-packages/lollms/personality.py", line 156, in __init__
    self.load_personality()
  File "/root/installer_files/lollms_env/lib/python3.10/site-packages/lollms/personality.py", line 273, in load_personality
    self._processor = module.Processor(self, callback=self.callback)
  File "/root/Documents/lollms/personalities_zoo/art/artbot/scripts/processor.py", line 77, in __init__
    super().__init__(
  File "/root/installer_files/lollms_env/lib/python3.10/site-packages/lollms/personality.py", line 1002, in __init__
    self.install()
  File "/root/Documents/lollms/personalities_zoo/art/artbot/scripts/processor.py", line 109, in install
    self.prepare()
  File "/root/Documents/lollms/personalities_zoo/art/artbot/scripts/processor.py", line 116, in prepare
    self.sd = self.get_sd().LollmsSD(self.personality.lollms_paths, "Artbot", max_retries=-1)
  File "/root/Documents/lollms/shared/auto_sd/lollms_sd.py", line 186, in __init__
    subprocess.Popen(script_path, cwd=self.sd_folder)
  File "/root/installer_files/lollms_env/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/root/installer_files/lollms_env/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: PosixPath('/root/Documents/lollms/shared/auto_sd/lollms_webui.sh')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/lollms-webui/api/__init__.py", line 870, in rebuild_personalities
    personality = AIPersonality(
  File "/root/installer_files/lollms_env/lib/python3.10/site-packages/lollms/personality.py", line 156, in __init__
    self.load_personality()
  File "/root/installer_files/lollms_env/lib/python3.10/site-packages/lollms/personality.py", line 273, in load_personality
    self._processor = module.Processor(self, callback=self.callback)
  File "/root/Documents/lollms/personalities_zoo/art/artbot/scripts/processor.py", line 77, in __init__
    super().__init__(
  File "/root/installer_files/lollms_env/lib/python3.10/site-packages/lollms/personality.py", line 1002, in __init__
    self.install()
  File "/root/Documents/lollms/personalities_zoo/art/artbot/scripts/processor.py", line 109, in install
    self.prepare()
  File "/root/Documents/lollms/personalities_zoo/art/artbot/scripts/processor.py", line 116, in prepare
    self.sd = self.get_sd().LollmsSD(self.personality.lollms_paths, "Artbot", max_retries=-1)
  File "/root/Documents/lollms/shared/auto_sd/lollms_sd.py", line 186, in __init__
    subprocess.Popen(script_path, cwd=self.sd_folder)
  File "/root/installer_files/lollms_env/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/root/installer_files/lollms_env/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: PosixPath('/root/Documents/lollms/shared/auto_sd/lollms_webui.sh')

**Comment by ParisNeo** [comment]
Hi. Artbot2 is renamed artbot, the version is in the yaml file.
It is advised for old users to remove the sd_auto file from their personal folder's share and reinstall the personality. The installer will install my custom version of auto1111's stable diffusion and run it when you talk to artbot.
If you still have an error don't hesitate to come to the discord channel, i check it more often than the github.

**Comment by agustin9014** [comment]
parisneo reinstall everything from 0 and I can't use arbot, the error is the one above

**Comment by ParisNeo** [comment]
Looks like you have some permission problems. Try running it with priviliges (sudo)

**Comment by agustin9014** [comment]
I reinstalled everything from 0 and ran with sudo but it's still the same. Also with docker-compose same problem

**Comment by ParisNeo** [comment]
It looks like you have a specific problem on your pc. What install method are you using ?
There are many ways to install on linix. Are you using conda?
