### ISSUE TITLE
at settings; cant type

### ISSUE THREAD

**Issue by superuben** [ParisNeo/lollms-webui#389]
when in the web-ui. the moment i start to interact with the text input field to search for a model, the body blanks out, in the console an error is visible;

index-57e478b9.js:1 TypeError: Cannot read properties of null (reading 'length')
    at Proxy.Zze (index-57e478b9.js:173:69753)
    at Ai (index-57e478b9.js:1:16676)
    at Ol.j [as fn] (index-57e478b9.js:1:41946)
    at Ol.run (index-57e478b9.js:1:5395)
    at Z.w.update (index-57e478b9.js:1:42693)
    at Rn (index-57e478b9.js:1:13464)
    at mf (index-57e478b9.js:1:15096)

**Comment by ParisNeo** [comment]
Hi, this should be fixed. In fact the zoo became too big and my old search method was very resource intensive. Now the search requires you to press enter after writing the text.
