### ISSUE TITLE
Upgrade from cpu to gpu

### ISSUE THREAD

**Issue by Juraj-HLUCH** [ParisNeo/lollms-webui#393]
## Current Behavior
I tried to update from cpu to gpu as showed in the video but I get a error in the console.

w10
nvidia 1060gtx 3 gb
AMD ryzen 7 1700

## Screenshots
ERROR:Lollms-WebUI:Exception on /upgrade_to_gpu [GET]
Traceback (most recent call last):
  File "C:\Users\Juraj\LoLLMs_webUI\installer_files\lollms_env\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Juraj\LoLLMs_webUI\installer_files\lollms_env\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Juraj\LoLLMs_webUI\installer_files\lollms_env\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Juraj\LoLLMs_webUI\installer_files\lollms_env\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Juraj\LoLLMs_webUI\lollms-webui\app.py", line 871, in upgrade_to_gpu
    res = subprocess.check_call(["conda", "install", "-c", "nvidia/label/cuda-11.7.0", "-c", "nvidia", "-c", "conda-forge",  "cuda-toolkit", "ninja", "git",  "--force-reinstall", "-y"])
  File "C:\Users\Juraj\LoLLMs_webUI\installer_files\lollms_env\lib\subprocess.py", line 364, in check_call
    retcode = call(*popenargs, **kwargs)
  File "C:\Users\Juraj\LoLLMs_webUI\installer_files\lollms_env\lib\subprocess.py", line 345, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\Juraj\LoLLMs_webUI\installer_files\lollms_env\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Juraj\LoLLMs_webUI\installer_files\lollms_env\lib\subprocess.py", line 1456, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

PS : this thing is awesome great job

**Comment by CapitaineThug** [comment]
Hi !

I had the same error when I tryed to upgrade from CPU to GPU. What resolved my issue was to install Anaconda or Miniconda manually on my system [()](https://www.anaconda.com/download). Normally, you should be able then to upgrade to GPU.
