### ISSUE TITLE
"app.py" suddenly returns "KeyError: 'db_path'" and stops

### ISSUE THREAD

**Issue by PHL4VIO** [ParisNeo/lollms-webui#404]
My local installation of LoLLMs, perfectly working until the last time I checked, from today refuses to start. This is the console output "app.py" gives out before stopping at "KeyError: 'db_path'"; I checked all paths and everything is still in place, including "database.db" in "/mnt/data/ai/lollms/databases".

----------------------Paths information-----------------------
personal_path:/mnt/data/ai/lollms
personal_configuration_path:/mnt/data/ai/lollms/configs
personal_databases_path:/mnt/data/ai/lollms/databases
personal_models_path:/mnt/data/ai/lollms/models
personal_user_infos_path:/mnt/data/ai/lollms/user_infos
personal_trainers_path:/mnt/data/ai/lollms/trainers
personal_trainers_path:/mnt/data/ai/lollms/trainers/gptqlora
personal_data_path:/mnt/data/ai/lollms/data
-------------------------------------------------------------
Checking for updates from /home/administrator/lollms-webui
update availability: True
Bindings zoo found in your personal space.
Pulling last personalities zoo
Already up to date.
Personalities zoo found in your personal space.
Pulling last personalities zoo
Already up to date.
Extensions zoo found in your personal space.
Pulling last Extensions zoo
Already up to date.
>Loading binding c_transformers. Please wait ...
Binding c_transformers loaded successfully.
>Loading model openbuddy-llama2-34b-v11.1-bf16-GGUF. Please wait ...
Building model
Model type : llama
Model built
Model openbuddy-llama2-34b-v11.1-bf16-GGUF loaded successfully.
Personality  gpt4all mounted successfully
Traceback (most recent call last):
  File "/home/administrator/lollms-webui/app.py", line 2463, in <module>
    bot = LoLLMsWebUI(args, app, socketio, config, config.file_path, lollms_paths)
  File "/home/administrator/lollms-webui/app.py", line 209, in __init__
    super().__init__(config, _socketio, config_file_path, lollms_paths)
  File "/home/administrator/lollms-webui/api/__init__.py", line 136, in __init__
    self.db_path = config["db_path"]
  File "/home/administrator/miniconda3/envs/lollms/lib/python3.10/site-packages/lollms/config.py", line 275, in __getitem__
    return self.config[key]
KeyError: 'db_path'

**Comment by PHL4VIO** [comment]
Please forget it: i reinstalled everything and everything now works. God only knows what I messed with.
