### ISSUE TITLE
Small bug when listing personalities (monkey_d_luffy)

### ISSUE THREAD

**Issue by ediweber** [ParisNeo/lollms-webui#489]
Hi there.

After some months of rl, I just installed lol9 and it seems to be a great step forward.
However there is a small bug which throws a error msg in the console which is quite annoying since i like it to be green blue and white instead of orange and red ;-)

Here's the error. Maybe you find time to fix: (or just remove that monkey ;-)

Listing all personalities
Couldn't load personality from E:\lol9\lollms-webui\zoos\personalities_zoo\anime\monkey_d_luffy ['charmap' codec can't decode byte 0x81 in position 149: character maps to <undefined>]
Traceback (most recent call last):
  File "e:\lol9\lollms-webui\lollms_core\lollms\server\endpoints\lollms_personalities_infos.py", line 88, in get_all_personalities
    config_data = yaml.load(config_file, Loader=yaml.FullLoader)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\lol9\installer_files\lollms_env\Lib\site-packages\yaml\__init__.py", line 79, in load
    loader = Loader(stream)
             ^^^^^^^^^^^^^^
  File "E:\lol9\installer_files\lollms_env\Lib\site-packages\yaml\loader.py", line 24, in __init__
    Reader.__init__(self, stream)
  File "E:\lol9\installer_files\lollms_env\Lib\site-packages\yaml\reader.py", line 85, in __init__
    self.determine_encoding()
  File "E:\lol9\installer_files\lollms_env\Lib\site-packages\yaml\reader.py", line 124, in determine_encoding
    self.update_raw()
  File "E:\lol9\installer_files\lollms_env\Lib\site-packages\yaml\reader.py", line 178, in update_raw
    data = self.stream.read(size)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\lol9\installer_files\lollms_env\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 149: character maps to <undefined>

**Comment by ParisNeo** [comment]
Hi. I am sorry. I added that persona yesterday and it is a japanese persona so the encoding was not working well.

Problem fixed. Now you can write personas with languages that are not standard without any problem.
