### ISSUE TITLE
A terabyte of python downloads and then.... boom!

### ISSUE THREAD

**Issue by 0wwafa** [ParisNeo/lollms-webui#542]
Starting LOLLMS Web UI...
      ___       ___           ___       ___       ___           ___      
     /\__\     /\  \         /\__\     /\__\     /\__\         /\  \     
    /:/  /    /::\  \       /:/  /    /:/  /    /::|  |       /::\  \    
   /:/  /    /:/\:\  \     /:/  /    /:/  /    /:|:|  |      /:/\ \  \   
  /:/  /    /:/  \:\  \   /:/  /    /:/  /    /:/|:|__|__   _\:\~\ \  \  
 /:/__/    /:/__/ \:\__\ /:/__/    /:/__/    /:/ |::::\__\ /\ \:\ \ \__\ 
 \:\  \    \:\  \ /:/  / \:\  \    \:\  \    \/__/~~/:/  / \:\ \:\ \/__/ 
  \:\  \    \:\  /:/  /   \:\  \    \:\  \         /:/  /   \:\ \:\__\   
   \:\  \    \:\/:/  /     \:\  \    \:\  \       /:/  /     \:\/:/  /   
    \:\__\    \::/  /       \:\__\    \:\__\     /:/  /       \::/  /    
     \/__/     \/__/         \/__/     \/__/     \/__/         \/__/     
 By ParisNeo
Trying to use Configuration at :global_paths_cfg.yaml
global_paths_cfg.yaml found!
Execution path : /content/lollms-webui
Local zoos folder found
----------------------Paths information-----------------------
personal_path:/content/personal_data
personal_configuration_path:/content/personal_data/configs
personal_discussions_path:/content/personal_data/discussion_databases
personal_skills_path:/content/personal_data/skill_databases
personal_models_path:/content/personal_data/models
personal_user_infos_path:/content/personal_data/user_infos
personal_trainers_path:/content/personal_data/trainers
personal_trainers_path:/content/personal_data/trainers/gptqlora
personal_data_path:/content/personal_data/data
custom_personalities_path:/content/personal_data/custom_personalities
custom_voices_path:/content/personal_data/custom_voices
-------------------------------------------------------------
----------------------Zoo information-----------------------
bindings_zoo_path:/content/lollms-webui/zoos/bindings_zoo
personalities_zoo_path:/content/lollms-webui/zoos/personalities_zoo
extensions_zoo_path:/content/lollms-webui/zoos/extensions_zoo
models_zoo_path:/content/lollms-webui/zoos/models_zoo
-------------------------------------------------------------
Lollms_core found in the app space.
Pulling last lollms_core
Already up to date.
safe_store_path found in the app space.
Pulling last safe_store_path
Already up to date.
Bindings zoo found in your personal space.
Pulling last bindings zoo
Already up to date.
Personalities zoo found in your personal space.
Pulling last personalities zoo
Already up to date.
Extensions zoo found in your personal space.
Pulling last Extensions zoo
Already up to date.
Models zoo found in your personal space.
Pulling last Models zoo
Already up to date.
>Loading binding python_llama_cpp. Please wait ...
Binding python_llama_cpp loaded successfully.
>Loading model Airoboros-M-7B-3.1.1-GGUF. Please wait ...
Traceback (most recent call last):
  File "/content/lollms-webui/zoos/bindings_zoo/python_llama_cpp/__init__.py", line 156, in build_model
    import llama_cpp_cuda_tensorcores
ModuleNotFoundError: No module named 'llama_cpp_cuda_tensorcores'

Couldn't load Llamacpp for cuda with tensorcores.
Reverting to CPU
Traceback (most recent call last):
  File "/content/lollms-webui/zoos/bindings_zoo/python_llama_cpp/__init__.py", line 156, in build_model
    import llama_cpp_cuda_tensorcores
ModuleNotFoundError: No module named 'llama_cpp_cuda_tensorcores'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/installer_files/lollms_env/lib/python3.11/site-packages/llama_cpp/llama_cpp.py", line 70, in _load_shared_library
    return ctypes.CDLL(str(_lib_path), **cdll_args)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/installer_files/lollms_env/lib/python3.11/ctypes/__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: libcuda.so.1: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/lollms-webui/zoos/bindings_zoo/python_llama_cpp/__init__.py", line 163, in build_model
    import llama_cpp
  File "/content/installer_files/lollms_env/lib/python3.11/site-packages/llama_cpp/__init__.py", line 1, in <module>
    from .llama_cpp import *
  File "/content/installer_files/lollms_env/lib/python3.11/site-packages/llama_cpp/llama_cpp.py", line 83, in <module>
    _lib = _load_shared_library(_lib_base_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/installer_files/lollms_env/lib/python3.11/site-packages/llama_cpp/llama_cpp.py", line 72, in _load_shared_library
    raise RuntimeError(f"Failed to load shared library '{_lib_path}': {e}")
RuntimeError: Failed to load shared library '/content/installer_files/lollms_env/lib/python3.11/site-packages/llama_cpp/libllama.so': libcuda.so.1: cannot open shared object file: No such file or directory

Couldn't load Llamacpp!!!
Binding broken. Try reinstalling it
Personality  lollms mounted successfully but no model is selected
Checking for updates from /content/lollms-webui
update availability: False
Checking for updates from /content/lollms-webui/lollms_core
update availability: False
Checking for updates from /content/lollms-webui/utilities/safe_store
update availability: False
Checking discussions database... ok
Your personal data is stored here :/content/personal_data
* - * - * - Starting services - * - * - *
 -> self.config.xtts_enable: False
 -> self.config.active_stt_service: None
/content/installer_files/lollms_env/lib/python3.11/site-packages/pydantic/_internal/_fields.py:160: UserWarning: Field "model_name" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
/content/installer_files/lollms_env/lib/python3.11/site-packages/pydantic/_internal/_fields.py:160: UserWarning: Field "model_url" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
INFO:     Started server process [5974]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
ERROR:    [Errno 99] error while attempting to bind on address ('::1', 9600, 0, 0): cannot assign requested address
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.

**Comment by jahangir1x** [comment]
try specifying host.
./linux_run.sh  --host 127.0.0.1 --port 9090

**Comment by ParisNeo** [comment]
this should work now.
