### ISSUE TITLE
Failed to install on Ubuntu 23.10

### ISSUE THREAD

**Issue by FireworkRocket** [ParisNeo/lollms-webui#548]
## Expected Behavior
Normal installation and operation

## Current Behavior
Very many errors when installing in the /home directory

## Steps to Reproduce
Clone the project in Ubuntu 23.10,
install pip, install python 3.12 and 3.11
run the install scripts
 
Terminal---------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Downloading Miniconda installer from https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  140M  100  140M    0     0   718k      0  0:03:19  0:03:19 --:--:-- 1106k

Installing Miniconda to /home/fireworkrocket/lollms-webui-main/scripts/linux/installer_files/miniconda3
Please wait...

ERROR: File or directory already exists: '/home/fireworkrocket/lollms-webui-main/scripts/linux/installer_files/miniconda3'
If you want to update an existing installation, use the -u option.

Miniconda installer not found.
Channels:
 - defaults
Platform: linux-64
Collecting package metadata (repodata.json): failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/fireworkrocket/lollms-webui-main/scripts/linux/installer_files/miniconda3/lib/python3.12/site-packages/conda/exception_handler.py", line 18, in __call__
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "/home/fireworkrocket/lollms-webui-main/scripts/linux/installer_files/miniconda3/lib/python3.12/site-packages/conda/cli/main.py", line 84, in main_subshell
        exit_code = do_call(args, parser)
                    ^^^^^^^^^^^^^^^^^^^^^
      File "/home/fireworkrocket/lollms-webui-main/scripts/linux/installer_files/miniconda3/lib/python3.12/site-packages/conda/cli/conda_argparse.py", line 200, in do_call
        result = getattr(module, func_name)(args, parser)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/fireworkrocket/lollms-webui-main/scripts/linux/installer_files/miniconda3/lib/python3.12/site-packages/conda/notices/core.py", line 132, in wrapper
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "/home/fireworkrocket/lollms-webui-main/scripts/linux/installer_files/miniconda3/lib/python3.12/site-packages/conda/cli/main_install.py", line 152, in execute
        return install(args, parser, "install")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/fireworkrocket/lollms-webui-main/scripts/linux/installer_files/miniconda3/lib/python3.12/site-packages/conda/cli/install.py", line 377, in install
        unlink_link_transaction = solver.solve_for_transaction(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/fireworkrocket/lollms-webui-main/scripts/linux/installer_files/miniconda3/lib/python3.12/site-packages/conda/core/solve.py", line 153, in solve_for_transaction
        unlink_precs, link_precs = self.solve_for_diff(
                                   ^^^^^^^^^^^^^^^^^^^^
      File "/home/fireworkrocket/lollms-webui-main/scripts/linux/installer_files/miniconda3/lib/python3.12/site-packages/conda/core/solve.py", line 222, in solve_for_diff
        final_precs = self.solve_final_state(
                      ^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/fireworkrocket/lollms-webui-main/scripts/linux/installer_files/miniconda3/lib/python3.12/site-packages/conda_libmamba_solver/solver.py", line 207, in solve_final_state
        index = IndexHelper(
                ^^^^^^^^^^^^
      File "/home/fireworkrocket/lollms-webui-main/scripts/linux/installer_files/miniconda3/lib/python3.12/site-packages/conda_libmamba_solver/index.py", line 136, in __init__
        self._index = self._load_channels()
                      ^^^^^^^^^^^^^^^^^^^^^
      File "/home/fireworkrocket/lollms-webui-main/scripts/linux/installer_files/miniconda3/lib/python3.12/site-packages/conda_libmamba_solver/index.py", line 332, in _load_channels
        jsons = {url: str(path) for (url, path) in executor.map(self._fetch_channel, urls)}
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/fireworkrocket/lollms-webui-main/scripts/linux/installer_files/miniconda3/lib/python3.12/concurrent/futures/_base.py", line 619, in result_iterator
        yield _result_or_cancel(fs.pop())
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/fireworkrocket/lollms-webui-main/scripts/linux/installer_files/miniconda3/lib/python3.12/concurrent/futures/_base.py", line 317, in _result_or_cancel
        return fut.result(timeout)
               ^^^^^^^^^^^^^^^^^^^
      File "/home/fireworkrocket/lollms-webui-main/scripts/linux/installer_files/miniconda3/lib/python3.12/concurrent/futures/_base.py", line 456, in result
        return self.__get_result()
               ^^^^^^^^^^^^^^^^^^^
      File "/home/fireworkrocket/lollms-webui-main/scripts/linux/installer_files/miniconda3/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
        raise self._exception
      File "/home/fireworkrocket/lollms-webui-main/scripts/linux/installer_files/miniconda3/lib/python3.12/concurrent/futures/thread.py", line 58, in run
        result = self.fn(*self.args, **self.kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/fireworkrocket/lollms-webui-main/scripts/linux/installer_files/miniconda3/lib/python3.12/site-packages/conda_libmamba_solver/index.py", line 254, in _fetch_channel
        json_path, _ = subdir_data.repo_fetch.fetch_latest_path()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/fireworkrocket/lollms-webui-main/scripts/linux/installer_files/miniconda3/lib/python3.12/site-packages/conda/gateways/repodata/__init__.py", line 749, in fetch_latest_path
        _, state = self.fetch_latest()
                   ^^^^^^^^^^^^^^^^^^^
      File "/home/fireworkrocket/lollms-webui-main/scripts/linux/installer_files/miniconda3/lib/python3.12/site-packages/conda/gateways/repodata/__init__.py", line 847, in fetch_latest
        raw_repodata = repo.repodata_parsed(cache.state)  # type: ignore
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/fireworkrocket/lollms-webui-main/scripts/linux/installer_files/miniconda3/lib/python3.12/site-packages/conda/gateways/repodata/jlap/interface.py", line 87, in repodata_parsed
        repodata_json_or_none = fetch.request_url_jlap_state(
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/fireworkrocket/lollms-webui-main/scripts/linux/installer_files/miniconda3/lib/python3.12/site-packages/conda/gateways/repodata/jlap/fetch.py", line 309, in request_url_jlap_state
        response = download_and_hash(
                   ^^^^^^^^^^^^^^^^^^
      File "/home/fireworkrocket/lollms-webui-main/scripts/linux/installer_files/miniconda3/lib/python3.12/site-packages/conda/gateways/repodata/jlap/fetch.py", line 243, in download_and_hash
        response = session.get(url, stream=True, timeout=timeout, headers=headers)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/fireworkrocket/lollms-webui-main/scripts/linux/installer_files/miniconda3/lib/python3.12/site-packages/requests/sessions.py", line 602, in get
        return self.request("GET", url, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/fireworkrocket/lollms-webui-main/scripts/linux/installer_files/miniconda3/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
        resp = self.send(prep, **send_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/fireworkrocket/lollms-webui-main/scripts/linux/installer_files/miniconda3/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
        r = adapter.send(request, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/fireworkrocket/lollms-webui-main/scripts/linux/installer_files/miniconda3/lib/python3.12/site-packages/requests/adapters.py", line 555, in send
        conn = self.get_connection_with_tls_context(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/fireworkrocket/lollms-webui-main/scripts/linux/installer_files/miniconda3/lib/python3.12/site-packages/requests/adapters.py", line 405, in get_connection_with_tls_context
        proxy_manager = self.proxy_manager_for(proxy)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/fireworkrocket/lollms-webui-main/scripts/linux/installer_files/miniconda3/lib/python3.12/site-packages/requests/adapters.py", line 264, in proxy_manager_for
        manager = self.proxy_manager[proxy] = SOCKSProxyManager(
                                              ^^^^^^^^^^^^^^^^^^
      File "/home/fireworkrocket/lollms-webui-main/scripts/linux/installer_files/miniconda3/lib/python3.12/site-packages/urllib3/contrib/socks.py", line 212, in __init__
        raise ValueError(f"Unable to determine SOCKS version from {proxy_url}")
    ValueError: Unable to determine SOCKS version from socks://127.0.0.1:7891/

`$ /home/fireworkrocket/lollms-webui-main/scripts/linux/installer_files/miniconda3/bin/conda install conda -y`

  environment variables:
                ALL_PROXY=<set>
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=/home/fireworkrocket/lollms-webui-
                          main/scripts/linux/installer_files/lollms_env
                CONDA_EXE=/home/fireworkrocket/lollms-webui-
                          main/scripts/linux/installer_files/miniconda3/bin/conda
             CONDA_PREFIX=/home/fireworkrocket/lollms-webui-
                          main/scripts/linux/installer_files/lollms_env
           CONDA_PREFIX_1=/home/fireworkrocket/lollms-webui-
                          main/scripts/linux/installer_files/miniconda3
    CONDA_PROMPT_MODIFIER=(/home/fireworkrocket/lollms-webui-
                          main/scripts/linux/installer_files/lollms_env)
         CONDA_PYTHON_EXE=/home/fireworkrocket/lollms-webui-
                          main/scripts/linux/installer_files/miniconda3/bin/python
               CONDA_ROOT=/home/fireworkrocket/lollms-webui-
                          main/scripts/linux/installer_files/miniconda3
              CONDA_SHLVL=2
           CURL_CA_BUNDLE=<not set>
               HTTP_PROXY=<set>
               LD_PRELOAD=<not set>
                 NO_PROXY=<set>
                     PATH=/home/fireworkrocket/lollms-webui-main/scripts/linux/installer_files/l
                          ollms_env/bin:/home/fireworkrocket/lollms-webui-main/scripts/linux/ins
                          taller_files/miniconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/s
                          bin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
         PYTHONNOUSERSITE=1
QTWEBENGINE_DICTIONARIES_PATH=/usr/share/hunspell-bdic/
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
                all_proxy=<set>
               http_proxy=<set>
                 no_proxy=<set>

     active environment : /home/fireworkrocket/lollms-webui-main/scripts/linux/installer_files/lollms_env
    active env location : /home/fireworkrocket/lollms-webui-main/scripts/linux/installer_files/lollms_env
            shell level : 2
       user config file : /root/.condarc
 populated config files : 
          conda version : 24.5.0
    conda-build version : not installed
         python version : 3.12.4.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=skylake
                          __conda=24.5.0=0
                          __glibc=2.38=0
                          __linux=6.5.0=0
                          __unix=0=0
       base environment : /home/fireworkrocket/lollms-webui-main/scripts/linux/installer_files/miniconda3  (writable)
      conda av data dir : /home/fireworkrocket/lollms-webui-main/scripts/linux/installer_files/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/fireworkrocket/lollms-webui-main/scripts/linux/installer_files/miniconda3/pkgs
                          /root/.conda/pkgs
       envs directories : /home/fireworkrocket/lollms-webui-main/scripts/linux/installer_files/miniconda3/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/24.5.0 requests/2.32.2 CPython/3.12.4 Linux/6.5.0-41-generic ubuntu/23.10 glibc/2.38 solver/libmamba conda-libmamba-solver/24.1.0 libmambapy/1.5.8 aau/0.4.4 c/. s/. e/.
                UID:GID : 0:0
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.
If you suspect this error is being caused by a malfunctioning plugin,
consider using the --no-plugins option to turn off plugins.

Example: conda --no-plugins install <package>

Alternatively, you can set the CONDA_NO_PLUGINS environment variable on
the command line to run the command without plugins enabled.

Example: CONDA_NO_PLUGINS=true conda install <package>

Upload did not complete.
已经是最新的。
Obtaining file:///home/fireworkrocket/lollms-webui-main/scripts/linux/lollms-webui/lollms_core
ERROR: file:///home/fireworkrocket/lollms-webui-main/scripts/linux/lollms-webui/lollms_core does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.
Obtaining file:///home/fireworkrocket/lollms-webui-main/scripts/linux/lollms-webui/utilities/safe_store
ERROR: file:///home/fireworkrocket/lollms-webui-main/scripts/linux/lollms-webui/utilities/safe_store does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.
Obtaining file:///home/fireworkrocket/lollms-webui-main/scripts/linux/lollms-webui/utilities/pipmaster
ERROR: file:///home/fireworkrocket/lollms-webui-main/scripts/linux/lollms-webui/utilities/pipmaster does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.
ERROR: Exception:
Traceback (most recent call last):
  File "/home/fireworkrocket/lollms-webui-main/scripts/linux/installer_files/lollms_env/lib/python3.11/site-packages/pip/_internal/cli/base_command.py", line 180, in exc_logging_wrapper
    status = run_func(*args)
             ^^^^^^^^^^^^^^^
  File "/home/fireworkrocket/lollms-webui-main/scripts/linux/installer_files/lollms_env/lib/python3.11/site-packages/pip/_internal/cli/req_command.py", line 245, in wrapper
    return func(self, options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fireworkrocket/lollms-webui-main/scripts/linux/installer_files/lollms_env/lib/python3.11/site-packages/pip/_internal/commands/install.py", line 377, in run
    requirement_set = resolver.resolve(
                      ^^^^^^^^^^^^^^^^^
  File "/home/fireworkrocket/lollms-webui-main/scripts/linux/installer_files/lollms_env/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 95, in resolve
    result = self._result = resolver.resolve(
                            ^^^^^^^^^^^^^^^^^
  File "/home/fireworkrocket/lollms-webui-main/scripts/linux/installer_files/lollms_env/lib/python3.11/site-packages/pip/_vendor/resolvelib/resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fireworkrocket/lollms-webui-main/scripts/linux/installer_files/lollms_env/lib/python3.11/site-packages/pip/_vendor/resolvelib/resolvers.py", line 397, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "/home/fireworkrocket/lollms-webui-main/scripts/linux/installer_files/lollms_env/lib/python3.11/site-packages/pip/_vendor/resolvelib/resolvers.py", line 173, in _add_to_criteria
    if not criterion.candidates:
  File "/home/fireworkrocket/lollms-webui-main/scripts/linux/installer_files/lollms_env/lib/python3.11/site-packages/pip/_vendor/resolvelib/structs.py", line 156, in __bool__
    return bool(self._sequence)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/fireworkrocket/lollms-webui-main/scripts/linux/installer_files/lollms_env/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__
    return any(self)
           ^^^^^^^^^
  File "/home/fireworkrocket/lollms-webui-main/scripts/linux/installer_files/lollms_env/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fireworkrocket/lollms-webui-main/scripts/linux/installer_files/lollms_env/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 44, in _iter_built
    for version, func in infos:
  File "/home/fireworkrocket/lollms-webui-main/scripts/linux/installer_files/lollms_env/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 297, in iter_index_candidate_infos
    result = self._finder.find_best_candidate(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fireworkrocket/lollms-webui-main/scripts/linux/installer_files/lollms_env/lib/python3.11/site-packages/pip/_internal/index/package_finder.py", line 890, in find_best_candidate
    candidates = self.find_all_candidates(project_name)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fireworkrocket/lollms-webui-main/scripts/linux/installer_files/lollms_env/lib/python3.11/site-packages/pip/_internal/index/package_finder.py", line 831, in find_all_candidates
    page_candidates = list(page_candidates_it)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fireworkrocket/lollms-webui-main/scripts/linux/installer_files/lollms_env/lib/python3.11/site-packages/pip/_internal/index/sources.py", line 194, in page_candidates
    yield from self._candidates_from_page(self._link)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fireworkrocket/lollms-webui-main/scripts/linux/installer_files/lollms_env/lib/python3.11/site-packages/pip/_internal/index/package_finder.py", line 791, in process_project_url
    index_response = self._link_collector.fetch_response(project_url)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fireworkrocket/lollms-webui-main/scripts/linux/installer_files/lollms_env/lib/python3.11/site-packages/pip/_internal/index/collector.py", line 461, in fetch_response
    return _get_index_content(location, session=self.session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fireworkrocket/lollms-webui-main/scripts/linux/installer_files/lollms_env/lib/python3.11/site-packages/pip/_internal/index/collector.py", line 364, in _get_index_content
    resp = _get_simple_response(url, session=session)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fireworkrocket/lollms-webui-main/scripts/linux/installer_files/lollms_env/lib/python3.11/site-packages/pip/_internal/index/collector.py", line 135, in _get_simple_response
    resp = session.get(
           ^^^^^^^^^^^^
  File "/home/fireworkrocket/lollms-webui-main/scripts/linux/installer_files/lollms_env/lib/python3.11/site-packages/pip/_vendor/requests/sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fireworkrocket/lollms-webui-main/scripts/linux/installer_files/lollms_env/lib/python3.11/site-packages/pip/_internal/network/session.py", line 520, in request
    return super().request(method, url, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fireworkrocket/lollms-webui-main/scripts/linux/installer_files/lollms_env/lib/python3.11/site-packages/pip/_vendor/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fireworkrocket/lollms-webui-main/scripts/linux/installer_files/lollms_env/lib/python3.11/site-packages/pip/_vendor/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fireworkrocket/lollms-webui-main/scripts/linux/installer_files/lollms_env/lib/python3.11/site-packages/pip/_vendor/cachecontrol/adapter.py", line 76, in send
    resp = super().send(request, stream, timeout, verify, cert, proxies)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fireworkrocket/lollms-webui-main/scripts/linux/installer_files/lollms_env/lib/python3.11/site-packages/pip/_vendor/requests/adapters.py", line 454, in send
    conn = self.get_connection(request.url, proxies)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fireworkrocket/lollms-webui-main/scripts/linux/installer_files/lollms_env/lib/python3.11/site-packages/pip/_vendor/requests/adapters.py", line 350, in get_connection
    proxy_manager = self.proxy_manager_for(proxy)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fireworkrocket/lollms-webui-main/scripts/linux/installer_files/lollms_env/lib/python3.11/site-packages/pip/_vendor/requests/adapters.py", line 215, in proxy_manager_for
    manager = self.proxy_manager[proxy] = SOCKSProxyManager(
                                          ^^^^^^^^^^^^^^^^^^
  File "/home/fireworkrocket/lollms-webui-main/scripts/linux/installer_files/lollms_env/lib/python3.11/site-packages/pip/_vendor/urllib3/contrib/socks.py", line 198, in __init__
    raise ValueError("Unable to determine SOCKS version from %s" % proxy_url)
ValueError: Unable to determine SOCKS version from socks://127.0.0.1:7891/
Linux run found
Linux update found
Creating a bin dir (required for llamacpp binding)
Select the default binding to be installed:
1) None (install the binding later)  5) Remote binding - open_router
2) Local binding - ollama	     6) Remote binding - open_ai
3) Local binding - python_llama_cpp  7) Remote binding - mistral_ai
4) Local binding - bs_exllamav2
#? 2
python: can't open file '/home/fireworkrocket/lollms-webui-main/scripts/linux/lollms-webui/zoos/bindings_zoo/ollama/__init__.py': [Errno 2] No such file or directory

*******************************************************************
*******************************************************************

root@fireworkrocket-HP-Pro-Tower-ZHAN-99-G9-Desktop-PC:/home/fireworkrocket/lollms-webui-main/scripts/linux# ^C
root@fireworkrocket-HP-Pro-Tower-ZHAN-99-G9-Desktop-PC:/home/fireworkrocket/lollms-webui-main/scripts/linux# 
Terminal---------------------------------------------------------------------------------------------------------------------------------------------------------------------------

## Possible Solution
No

## Context
No

## Screenshots
![截图 2024-06-29 00-29-38](https://github.com/ParisNeo/lollms-webui/assets/120904221/2bead490-e83e-403c-90e5-e4b6e1c4130e)

![截图 2024-06-29 00-29-28](https://github.com/ParisNeo/lollms-webui/assets/120904221/51ba1a55-debe-401d-9706-faf98ca07d8d)

![截图 2024-06-29 00-28-23](https://github.com/ParisNeo/lollms-webui/assets/120904221/38e2ab85-8a69-48c9-a4a2-cbd74496cce4)

**Comment by ParisNeo** [comment]
Hi, sorry for delay.
In fact you are trying to instll using the install scripts in scripts folder. This is not the way to install.
Go to the release page, grub your linux installler script, put it in an empty folder then execute it. It will install a portable miniconda, then clone the repo and then install all the requirements and build the linux_run.sh script used to start the app.

**Comment by FireworkRocket** [comment]
ok，it's working ，thanks (^-^)
