### ISSUE TITLE
No module named 'git'

### ISSUE THREAD

**Issue by LMcontent** [ParisNeo/lollms-webui#549]
## Expected Behavior
Starting lollms-webui 9.8 . (Win 10)

## Current Behavior

*error_1*

Starting LOLLMS Web UI...
By ParisNeo
Traceback (most recent call last):
  File "C:\Lollms\lollms-webui\app.py", line 8, in <module>
    from lollms.utilities import PackageManager
  File "c:\lollms\lollms-webui\lollms_core\lollms\utilities.py", line 36, in <module>
    import git
ModuleNotFoundError: No module named 'git'

*error_2*

Starting LOLLMS Web UI...
By ParisNeo
Checking ParisNeo libraries installation OK
defusedxml is not installed. Installing..
Collecting defusedxml
Downloading defusedxml-0.7.1-py2.py3-none-any.whl.metadata (32 kB) Downloading defusedxml-0.7.1-py2.py3-none-any.whl (25 kB)
Installing collected packages: defusedxml
Successfully installed defusedxml-0.7.1 Traceback (most recent call last):
File "C:\Lollms\lollms-webui\app.py", line 53, in <module>
import psutil
ModuleNotFoundError: No module named 'psutil'

## Steps to Reproduce

0. (I have a Anaconda for my projects)
1. I create C:\Lollms.
2. I start C:\Lollms\win_install.bat and see all installation.
3. I'm launching C:\Lollms\win_run.bat and saw error - no have git module. *error_1*
4. I add "GitPython" module in my Anaconda Navigator in enviroment "lollms_env"
5. I retry  launching win_install.bat and saw error - no have psutil module.*error_2*
6. I add "psutil" module in my Anaconda Navigator in enviroment "lollms_env"
7.  I retry  launching win_install.bat and all is starting OK.

## Possible Solution
Maybe you make a new script for users Anaconda.

## Context
If Anaconda is installed, then maybe it conflicts with Miniconda?
I see  in my Anaconda Navigator two environment: miniconda3 and lollms_env. It's probably can be problem for Anaconda's environment and Miniconda's environment.

## Screenshots

**Comment by fultonm** [comment]
Same. I also used the root of my C drive to install.
