### ISSUE TITLE
Installation Step List for Win10 users

### ISSUE THREAD

**Issue by Hoooooooocc** [ParisNeo/lollms-webui#581]
This looks like a very outstanding project, thanks for your great job. 
For some users like me, Newcomers to the field of artificial intelligence, it is still difficult to deploy this .
Can directly provide the installation Step List for Windows 10 users?

my path "main_v1\app.py" equivalent to "lollm_webui\app.py".
This is one of the big problems I have encountered ( when I run "python main_v1\app.py"):

      a few lines about: ' xxx connect : OK '

      Personalities zoo found in your personal space.
      Pulling last personalities zoo ⠇  fatal: unable to access 'https://github.com/ParisNeo/lollms_personalities_zoo.git/': OpenSSL SSL_r
      Models zoo found in your personal space.
      Pulling last Models zoo ⠧  fatal: unable to access 'https://github.com/ParisNeo/models_zoo.git/': Failed to connect to github.com po
      server
      No binding selected        
      [[[ app.py lollms_path ]]]  Global paths configuration Path: global_paths_cfg.yaml
      Personal Configuration Path: D:\Projs\LLM_LoUI\main_v1\configs\configs
      Personal Data Path: D:\Projs\LLM_LoUI\main_v1\configs\data
      Personal Databases Path: D:\Projs\LLM_LoUI\main_v1\configs\discussion_databases   
      Personal Skills Path: D:\Projs\LLM_LoUI\main_v1\configs\skill_databases
      Personal Models Path: D:\Projs\LLM_LoUI\main_v1\configs\models
      Personal Uploads Path: D:\Projs\LLM_LoUI\main_v1\configs\uploads
      Personal Log Path: D:\Projs\LLM_LoUI\main_v1\configs\logs
      Personal outputs Path: D:\Projs\LLM_LoUI\main_v1\configs\outputs
      Bindings Zoo Path: D:\Projs\LLM_LoUI\main_v1\configs\zoos\bindings_zoo
      Personalities Zoo Path: D:\Projs\LLM_LoUI\main_v1\configs\zoos\personalities_zoo
      Personal user infos path: D:\Projs\LLM_LoUI\main_v1\configs\user_infos
      Personal trainers path: D:\Projs\LLM_LoUI\main_v1\configs\trainers
      Personal gptqlora trainer path: D:\Projs\LLM_LoUI\main_v1\configs\trainers\gptqlora
      Personal services path: D:\Projs\LLM_LoUI\main_v1\configs\services
      Personal STT services path: D:\Projs\LLM_LoUI\main_v1\configs\services\stt
      Personal TTS services path: D:\Projs\LLM_LoUI\main_v1\configs\services\tts
      Personal TTI services path: D:\Projs\LLM_LoUI\main_v1\configs\services\tti
      Personal TTM services path: D:\Projs\LLM_LoUI\main_v1\configs\services\ttm
      Applications zoo path: D:\Projs\LLM_LoUI\main_v1\configs\apps_zoo
      Couldn't load personality. Please verify your configuration file at D:\Projs\LLM_LoUI\main_v1\configs\configs or use the next menu t
      Binding returned this exception : The 'lollms' distribution was not found and is required by the application
      Traceback (most recent call last):
        File "D:\Projs\LLM_LoUI\main_v1\lollms\app.py", line 711, in mount_personality
          personality = PersonalityBuilder(self.lollms_paths, self.config, self.model, self, callback=callback).build_personality(id)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "D:\Projs\LLM_LoUI\main_v1\lollms\personality.py", line 5334, in build_personality
          self.personality = AIPersonality(
                             ^^^^^^^^^^^^^^
        File "D:\Projs\LLM_LoUI\main_v1\lollms\personality.py", line 156, in __init__
          self._version = pkg_resources.get_distribution('lollms').version
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "D:\Projs\LLM_LoUI\env\Lib\site-packages\pkg_resources\__init__.py", line 542, in get_distribution
          dist = get_provider(dist)  # type: ignore[assignment]
                 ^^^^^^^^^^^^^^^^^^
        File "D:\Projs\LLM_LoUI\env\Lib\site-packages\pkg_resources\__init__.py", line 424, in get_provider
          return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^
        File "D:\Projs\LLM_LoUI\env\Lib\site-packages\pkg_resources\__init__.py", line 1062, in require
          needed = self.resolve(parse_requirements(requirements))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "D:\Projs\LLM_LoUI\env\Lib\site-packages\pkg_resources\__init__.py", line 889, in resolve
          dist = self._resolve_dist(
                 ^^^^^^^^^^^^^^^^^^^
        File "D:\Projs\LLM_LoUI\env\Lib\site-packages\pkg_resources\__init__.py", line 930, in _resolve_dist
          raise DistributionNotFound(req, requirers) 
        ( Omit the remaining part )

**Comment by ParisNeo** [comment]
Thaznks for your message.
To install lollms on windows, you can just use the provided .bat installer.
make sure you have already installed git.
put the .bat file inside an empty folder where you want to install lollms then run it. it should clone the repo and install dependancies etc.

The other way would be to clone the repo with 👍 
```bash
git clone --recurse-submodules https://github.com/ParisNeo/lollms-webui.git
```

make sure you have python 3.11 installed, or you can create a conda environment with python 3.11 and activate it.

install requirements
```bash
pip install --upgrade requirements.txt
```

then you can run it wiuth:
```bash
python app.py
```

Best regards

**Comment by SiL3NC3** [comment]
I get an error:

![Image](https://github.com/user-attachments/assets/0ca7203c-a6b3-49b0-93c4-c7cde5bb113b)

**Comment by sjbaird** [comment]
I agree this is a great project with a lot of great features, however there are many looping directory calls that will end up creating environments inside the environment. Or expect the whole script to be inside another folder called lollms. I can get it to run and start without any extra folders or files then it starts adding buried folders and not being able to figure out which one its looking for.

Sometimes I will get everything working and then when I want to add one more binding it will some how not be able to find the files it just used to process the first binding then when you get that one situated the next thing you know is some random clean up script deleted half the files you just got working.

It also did not install in the directed folder it always wants to install in C:\lollms-webUI or in the user folder.
This is one of the many errors that are created 
The build and compound each other.

Select the default binding to be installed:
1) None (install the binding later)
2) Local binding - ollama
3) Local binding - python_llama_cpp
4) Local binding - bs_exllamav2
5) Remote binding - groq
6) Remote binding - open_router
7) Remote binding - open_ai
8) Remote binding - mistral_ai
9) Remote binding - gemini
10) Remote binding - vllm
11) Remote binding - xAI
12) Remote binding - elf
13) Remote binding - remote lollms
Type the number of your choice and press Enter: 2
Traceback (most recent call last):
  File "C:\Windows\System32\lollms-webui\zoos\bindings_zoo\ollama\__init__.py", line 18, in <module>
    from lollms.binding import LLMBinding, LOLLMSConfig, BindingType
  File "c:\windows\system32\lollms-webui\lollms_core\lollms\binding.py", line 27, in <module>
    from lollms.utilities import show_message_dialog
  File "c:\windows\system32\lollms-webui\lollms_core\lollms\utilities.py", line 35, in <module>
    import git
ModuleNotFoundError: No module named 'git'
Installation complete.
Restored to original path: C:\Windows\System32
Press any key to continue . . .
